# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Danial Behzadi <dani.behzi@ubuntu.com>, 2020
# alireza jamshidi <alirezajam98@gmail.com>, 2020
# Mahdy Mirzade <me@mahdym.ir>, 2021
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-05-27 11:18+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Mahdy Mirzade <me@mahdym.ir>, 2021\n"
"Language-Team: Persian (https://www.transifex.com/calamares/teams/20061/fa/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: fa\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "نصب بسته‌ها."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "در حال پردازش بسته‌ها (%(count)d/%(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "در حال نصب یک بسته."
msgstr[1] "در حال نصب %(num)d بسته."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "در حال برداشتن یک بسته."
msgstr[1] "در حال برداشتن %(num)d بسته."

#: src/modules/packages/main.py:725 src/modules/packages/main.py:737
#: src/modules/packages/main.py:765
msgid "Package Manager error"
msgstr "خطای مدیر بسته"

#: src/modules/packages/main.py:726
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"مدیر بسته نتوانست برای بروزرسانی ها آماده شود، دستور <pre>{!s}</pre> با خطای"
" {!s} مواجه شد."

#: src/modules/packages/main.py:738
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"مدیر بسته نتوانست سامانه را بروز کند. دستور <pre>{!s}</pre> با خطای {!s} "
"مواجه شد."

#: src/modules/packages/main.py:766
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"مدیر بسته نتوانست تغییرات را برای نصب سامانه انجام دهد. دستور "
"<pre>{!s}</pre> با خطای {!s} مواجه شد."

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "در حال ذخیرهٔ پیکربندی شبکه."

#: src/modules/networkcfg/main.py:105 src/modules/initcpiocfg/main.py:235
#: src/modules/initcpiocfg/main.py:239 src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:229 src/modules/fstab/main.py:394
#: src/modules/fstab/main.py:400 src/modules/fstab/main.py:428
#: src/modules/initramfscfg/main.py:85 src/modules/initramfscfg/main.py:89
#: src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "خطای پیکربندی"

#: src/modules/networkcfg/main.py:106 src/modules/initcpiocfg/main.py:240
#: src/modules/openrcdmcryptcfg/main.py:77 src/modules/localecfg/main.py:141
#: src/modules/fstab/main.py:401 src/modules/initramfscfg/main.py:90
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "هیچ نقطهٔ اتّصال ریشه‌ای برای استفادهٔ <pre>{!s}</pre> داده نشده."

#: src/modules/initcpiocfg/main.py:28
msgid "Configuring mkinitcpio."
msgstr "پیکربندی mkinitcpio."

#: src/modules/initcpiocfg/main.py:236 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/mount/main.py:230 src/modules/fstab/main.py:395
#: src/modules/initramfscfg/main.py:86 src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "هیچ افرازی برای استفادهٔ <pre>{!s}</pre> تعریف نشده."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "درحال ایجاد initramfs با mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "شکست در اجرا mkinitfs روی هدف"

#: src/modules/mkinitfs/main.py:50 src/modules/dracut/main.py:50
msgid "The exit code was {}"
msgstr "رمز خروج {} بود"

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "در حال پیکربندی خدمت dmcrypt OpenRC."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "در حال پر کردن سامانه‌پرونده‌ها."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "آرسینک با رمز خطای {} شکست خورد."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "در حال بسته‌گشایی تصویر {}/{}، پروندهٔ {}/{}"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "در حال شروع بسته‌گشایی {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "شکست در بسته‌گشایی تصویر {}"

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "هیچ نقطهٔ اتّصالی برای افراز ریشه وجود ندارد"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr ""

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "نقطهٔ اتّصال بد برای افراز ریشه"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr ""

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr ""

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr ""

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "کرنل کنونیتان از سامانه‌پروندهٔ {} ({}) پشتیبانی نمی‌کند"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "سامانهٔ پروندهٔ مبدأ {} وجود ندارد"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr "شکست در یافتن unsquashfs. مطمئن شوید بسته squashfs-tools نصب است."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "مقصد {} در سامانهٔ هدف، یک شاخه نیست"

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd services"
msgstr "در حال پیکربندی خدمات سیستم‌دی"

#: src/modules/services-systemd/main.py:59
#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "نمی‌توان خدمت را دستکاری کرد"

#: src/modules/services-systemd/main.py:60
msgid ""
"<code>systemctl {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"فراخوانی <code>systemctl {arg!s}</code> در chroot رمز خطای {num!s} را "
"برگرداند."

#: src/modules/services-systemd/main.py:63
#: src/modules/services-systemd/main.py:69
msgid "Cannot enable systemd service <code>{name!s}</code>."
msgstr "نمی‌توان خدمت سیستم‌دی <code>{name!s}</code> را به کار انداخت."

#: src/modules/services-systemd/main.py:65
msgid "Cannot enable systemd target <code>{name!s}</code>."
msgstr "نمی‌توان هدف سیستم‌دی <code>{name!s}</code> را به کار انداخت."

#: src/modules/services-systemd/main.py:67
msgid "Cannot enable systemd timer <code>{name!s}</code>."
msgstr "نمی‌توان تایمر سیستم‌دی <code>{name!s}</code> را به کار انداخت."

#: src/modules/services-systemd/main.py:71
msgid "Cannot disable systemd target <code>{name!s}</code>."
msgstr "نمی‌توان خدمت سیستم‌دی <code>{name!s}</code> را از کار انداخت."

#: src/modules/services-systemd/main.py:73
msgid "Cannot mask systemd unit <code>{name!s}</code>."
msgstr "نمی‌توان واحد سیستم‌دی <code>{name!s}</code> را پوشاند."

#: src/modules/services-systemd/main.py:75
msgid ""
"Unknown systemd commands <code>{command!s}</code> and "
"<code>{suffix!s}</code> for unit {name!s}."
msgstr ""
"دستورات ناشناختهٔ سیستم‌دی <code>{command!s}</code> و "
"<code>{suffix!s}</code> برای واحد {name!s}."

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "کار پایتونی الکی."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "گام پایتونی الکی {}"

#: src/modules/bootloader/main.py:43
msgid "Install bootloader."
msgstr "نصب بارکنندهٔ راه‌اندازی."

#: src/modules/bootloader/main.py:614
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""

#: src/modules/bootloader/main.py:782
msgid "Bootloader installation error"
msgstr "خطای نصب بوت لودر"

#: src/modules/bootloader/main.py:783
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"بوت لودر نتوانست نصب شود. دستور <pre>{!s}</pre> برای نصب با خطای {!s} مواجه "
"شد."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "پیکربندی مکانها"

#: src/modules/mount/main.py:42
msgid "Mounting partitions."
msgstr "در حال سوار کردن افرازها."

#: src/modules/mount/main.py:88 src/modules/mount/main.py:124
msgid "Internal error mounting zfs datasets"
msgstr ""

#: src/modules/mount/main.py:100
msgid "Failed to import zpool"
msgstr ""

#: src/modules/mount/main.py:116
msgid "Failed to unlock zpool"
msgstr ""

#: src/modules/mount/main.py:133 src/modules/mount/main.py:138
msgid "Failed to set zfs mountpoint"
msgstr ""

#: src/modules/mount/main.py:253
msgid "zfs mounting error"
msgstr ""

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "در حال پیکربندی زمینهٔ پلی‌موث"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "در حال نوشتن fstab."

#: src/modules/fstab/main.py:429
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"هیچ تنظیمات <pre>{!s}</pre> برای استفاده برای <pre>{!s}</pre> داده نشده است."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "پیکربندی خدمات OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "نمی‌توان خدمت {name!s} را به سطح اجرایی {level!s} افزود."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "نمی‌توان خدمت {name!s} را از سطح اجرایی {level!s} برداشت."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"دستور سرویس <code>{arg!s}</code> برای سرویس {name!s} در سطح اجرای {level!s}"
"  ناشناخته است."

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"فراخوانی <code>rc-update {arg!s}</code> در chroot کد خطای {num!s} را "
"برگرداند."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "سطح اجرایی هدف وجود ندارد."

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"مسیر برای سطح اجرای {level!s} برابر <code>{path!s}</code> است، که وجود "
"ندارد."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "خدمت هدف وجود ندارد"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"مسیر برای سرویس {name!s} برابر <code>{path!s}</code> است، که وجود ندارد."

#: src/modules/dracut/main.py:27
msgid "Creating initramfs with dracut."
msgstr "در حال ایجاد initramfs با dracut."

#: src/modules/dracut/main.py:49
msgid "Failed to run dracut on the target"
msgstr "شکست در اجرای dracut روی هدف"

#: src/modules/grubcfg/main.py:28
msgid "Configure GRUB."
msgstr "در حال پیکربندی گراب."

#: src/modules/displaymanager/main.py:524
msgid "Cannot write KDM configuration file"
msgstr "نمی‌توان پروندهٔ پیکربندی KDM را نوشت"

#: src/modules/displaymanager/main.py:525
msgid "KDM config file {!s} does not exist"
msgstr "پروندهٔ پیکربندی {!s} وجود ندارد"

#: src/modules/displaymanager/main.py:586
msgid "Cannot write LXDM configuration file"
msgstr "نمی‌توان پروندهٔ پیکربندی LXDM را نوشت"

#: src/modules/displaymanager/main.py:587
msgid "LXDM config file {!s} does not exist"
msgstr "پروندهٔ پیکربندی {!s} وجود ندارد"

#: src/modules/displaymanager/main.py:670
msgid "Cannot write LightDM configuration file"
msgstr "نمی‌توان پروندهٔ پیکربندی LightDM را نوشت"

#: src/modules/displaymanager/main.py:671
msgid "LightDM config file {!s} does not exist"
msgstr "پروندهٔ پیکربندی {!s} وجود ندارد"

#: src/modules/displaymanager/main.py:745
msgid "Cannot configure LightDM"
msgstr "نمی‌توان LightDM را پیکربندی کرد"

#: src/modules/displaymanager/main.py:746
msgid "No LightDM greeter installed."
msgstr "هیچ خوش‌آمدگوی LightDMای نصب نشده."

#: src/modules/displaymanager/main.py:777
msgid "Cannot write SLIM configuration file"
msgstr "نمی‌توان پروندهٔ پیکربندی LightDM را نوشت"

#: src/modules/displaymanager/main.py:778
msgid "SLIM config file {!s} does not exist"
msgstr "پروندهٔ پیکربندی {!s} وجود ندارد"

#: src/modules/displaymanager/main.py:992
msgid "No display managers selected for the displaymanager module."
msgstr "هیچ مدیر نمایشی برای پیمانهٔ displaymanager گزیده نشده."

#: src/modules/displaymanager/main.py:993
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"فهرست مدیریت صفحه نمایش ها خالی بوده یا در محل ذخیره داده و "
"displaymanager.conf تعریف نشده است."

#: src/modules/displaymanager/main.py:1075
msgid "Display manager configuration was incomplete"
msgstr "پیکربندی مدیر نمایش کامل نبود"

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "در حال پیکربندی initramfs."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "در حال تنظیم ساعت سخت‌افزاری."

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "داده‌های نصب"
