# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# ブラシックデービッド, 2019
# Takefumi Nagata, 2019
# UTUMI Hirosi <utuhiro78@yahoo.co.jp>, 2023
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-28 22:49+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: UTUMI Hirosi <utuhiro78@yahoo.co.jp>, 2023\n"
"Language-Team: Japanese (https://app.transifex.com/calamares/teams/20061/ja/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "ブートローダーをインストール"

#: src/modules/bootloader/main.py:644
msgid "Failed to install grub, no partitions defined in global storage"
msgstr "grub のインストールに失敗しました。グローバルストレージにパーティションが定義されていません"

#: src/modules/bootloader/main.py:899
msgid "Bootloader installation error"
msgstr "ブートローダーのインストールエラー"

#: src/modules/bootloader/main.py:900
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"ブートローダーをインストールできませんでした。インストールコマンド <pre>{!s}</pre> がエラーコード {!s} を返しました。"

#: src/modules/displaymanager/main.py:509
msgid "Cannot write LXDM configuration file"
msgstr "LXDMの設定ファイルに書き込みができません"

#: src/modules/displaymanager/main.py:510
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM 設定ファイル {!s} が存在しません"

#: src/modules/displaymanager/main.py:598
msgid "Cannot write LightDM configuration file"
msgstr "LightDMの設定ファイルに書き込みができません"

#: src/modules/displaymanager/main.py:599
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM 設定ファイル {!s} が存在しません"

#: src/modules/displaymanager/main.py:684
msgid "Cannot configure LightDM"
msgstr "LightDMの設定ができません"

#: src/modules/displaymanager/main.py:685
msgid "No LightDM greeter installed."
msgstr "LightDM greeter がインストールされていません。"

#: src/modules/displaymanager/main.py:716
msgid "Cannot write SLIM configuration file"
msgstr "SLIMの設定ファイルに書き込みができません"

#: src/modules/displaymanager/main.py:717
msgid "SLIM config file {!s} does not exist"
msgstr "SLIM 設定ファイル {!s} が存在しません"

#: src/modules/displaymanager/main.py:935
msgid "No display managers selected for the displaymanager module."
msgstr "ディスプレイマネージャが選択されていません。"

#: src/modules/displaymanager/main.py:936
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr "globalstorage と displaymanager.conf の両方で、displaymanagers リストが空か未定義です。"

#: src/modules/displaymanager/main.py:1023
msgid "Display manager configuration was incomplete"
msgstr "ディスプレイマネージャの設定が不完全です"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "dracutとinitramfsを作成しています。"

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "dracut の実行に失敗しました"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr "ターゲットで dracut を実行できませんでした。リターンコード: {return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Dummy python job."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "Dummy python step {}"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "fstabを書き込んでいます。"

#: src/modules/fstab/main.py:377 src/modules/fstab/main.py:383
#: src/modules/fstab/main.py:411 src/modules/initcpiocfg/main.py:256
#: src/modules/initcpiocfg/main.py:260 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:329 src/modules/networkcfg/main.py:105
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "コンフィグレーションエラー"

#: src/modules/fstab/main.py:378 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:330 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "<pre>{!s}</pre> に使用するパーティションが定義されていません。"

#: src/modules/fstab/main.py:384 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr " <pre>{!s}</pre> を使用するのにルートマウントポイントが与えられていません。"

#: src/modules/fstab/main.py:412
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr "<pre>{!s}</pre> が使用する <pre>{!s}</pre> 設定が指定されていません。"

#: src/modules/grubcfg/main.py:29
msgid "Configure GRUB."
msgstr "GRUBを設定にします。"

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "ハードウェアクロックの設定"

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "mkinitcpioを設定しています。"

#: src/modules/initcpiocfg/main.py:257
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "<pre>initcpiocfg</pre> にパーティションが定義されていません。"

#: src/modules/initcpiocfg/main.py:261
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "<pre>initcpiocfg</pre> のルートマウントポイントがありません"

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "initramfsを設定しています。"

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "ロケールを設定しています。"

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "mkinitfsを使用してinitramfsを作成します。"

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "ターゲットでmkinitfsを実行できませんでした"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "停止コードは {} でした"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "パーティションのマウント。"

#: src/modules/mount/main.py:164 src/modules/mount/main.py:200
msgid "Internal error mounting zfs datasets"
msgstr "zfs データセットのマウントで内部エラーが発生"

#: src/modules/mount/main.py:176
msgid "Failed to import zpool"
msgstr "zpool のインポートに失敗しました"

#: src/modules/mount/main.py:192
msgid "Failed to unlock zpool"
msgstr "zpool のロック解除に失敗しました。"

#: src/modules/mount/main.py:209 src/modules/mount/main.py:214
msgid "Failed to set zfs mountpoint"
msgstr "zfs マウントポイントの設定に失敗しました"

#: src/modules/mount/main.py:365
msgid "zfs mounting error"
msgstr "zfs のマウントでエラー"

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "ネットワーク設定を保存しています。"

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "OpenRC dmcryptサービスを設定しています。"

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "パッケージのインストール"

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "パッケージを処理しています (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] " %(num)d パッケージをインストールしています。"

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] " %(num)d パッケージを削除しています。"

#: src/modules/packages/main.py:740 src/modules/packages/main.py:752
#: src/modules/packages/main.py:780
msgid "Package Manager error"
msgstr "パッケージマネージャーのエラー"

#: src/modules/packages/main.py:741
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"パッケージマネージャーはアップデートを準備できませんでした。コマンド <pre>{!s}</pre> はエラーコード {!s} を返しました。"

#: src/modules/packages/main.py:753
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"パッケージマネージャーはシステムをアップデートできませんでした。 コマンド <pre>{!s}</pre> はエラーコード {!s} を返しました。"

#: src/modules/packages/main.py:781
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"パッケージマネージャーはインストールされているシステムに変更を加えられませんでした。コマンド <pre>{!s}</pre> はエラーコード {!s} "
"を返しました。"

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Plymouthテーマを設定"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "データのインストール。"

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "OpenRCサービスを設定"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "ランレベル  {level!s} にサービス {name!s} が追加できません。"

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "ランレベル  {level!s} からサービス {name!s} が削除できません。"

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"ランレベル {level!s} 内のサービス {name!s} に対する未知のサービスアクション <code>{arg!s}</code>。"

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "サービスが変更できません"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr "chrootで <code>rc-update {arg!s}</code> を呼び出すとエラーコード {num!s} が返されました。"

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "ターゲットとするランレベルは存在しません"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "ランレベル {level!s} のパスが <code>{path!s}</code> です。これは存在しません。"

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "ターゲットとするサービスは存在しません"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "サービス {name!s} のパスが <code>{path!s}</code> です。これは存在しません。"

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "systemd ユニットの設定"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "ユニットを変更できません"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"chroot での <code>systemctl {_action!s}</code> コールが、エラーコード {_exit_code!s}. "
"を返しました。"

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "{_action!s} systemd ユニット <code>{_name!s}</code> を実行できません。"

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "ファイルシステムに書き込んでいます。"

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "エラーコード {} によりrsyncを失敗。"

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "イメージ {}/{}, ファイル {}/{} を解凍しています"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "{} の解凍を開始しています"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "イメージ  \"{}\" の展開に失敗"

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "ルートパーティションのためのマウントポイントがありません"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage に \"rootMountPoint\" キーがありません。"

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "ルートパーティションのためのマウントポイントが不正です"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint が \"{}\" になっていて存在しません。"

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "不適切な unpackfs の設定"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "設定情報がありません。"

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "\"{}\" ({}) のファイルシステムは、現在のカーネルではサポートされていません"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "ソースファイルシステム  \"{}\" は存在しません"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr "unsquashfs が見つかりませんでした。squashfs-tools パッケージがインストールされているか確認してください。"

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "ターゲットシステムの宛先 \"{}\" はディレクトリではありません"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "ZFS で生成されたホスト ID をコピーしています。"
